"""
mcp_gateway/models/mcp_agent_memory.py

Session memory model for storing conversation summaries for context injection.

Key classes:
  AgentMemory — Stores LLM-generated 3-sentence summary of past sessions

Dependencies:
  - mcp.agent — agent in memory
  - res.users — user whose conversation was summarized
  - mcp.session — session that was summarized

Developer notes:
  - Auto-pruned to last 10 per agent+user pair (oldest deleted on new insert)
  - Summaries injected into system prompt during gateway.run()
  - Generated by gateway.summarize_session() after session completes
"""

import logging
from odoo import fields, models, api, _

_logger = logging.getLogger(__name__)


class AgentMemory(models.Model):
    """
    Agent Memory (mcp.agent.memory)

    Stores LLM-generated 3-sentence summaries of past sessions.
    Used to provide agents context about user history.

    Relationships:
      - BelongsTo: mcp.agent via agent_id
      - BelongsTo: res.users via user_id
      - BelongsTo: mcp.session via session_id

    Business rules:
      - Auto-limited to last 10 memories per agent+user pair
      - Deleted when agent or user deleted
    """

    _name = 'mcp.agent.memory'
    _description = _('Agent Session Memory')
    _order = 'create_date DESC'

    agent_id = fields.Many2one(
        comodel_name='mcp.agent',
        string=_('Agent'),
        required=True,
        readonly=True,
        ondelete='cascade',
    )
    user_id = fields.Many2one(
        comodel_name='res.users',
        string=_('User'),
        required=True,
        readonly=True,
        ondelete='cascade',
    )
    session_id = fields.Many2one(
        comodel_name='mcp.session',
        string=_('Session'),
        required=True,
        readonly=True,
        ondelete='cascade',
        help=_('Session that generated this memory'),
    )
    summary = fields.Text(
        string=_('Summary'),
        required=True,
        readonly=True,
        help=_('3-sentence LLM-generated summary of session'),
    )

    @api.model_create_multi
    def create(self, vals_list):
        """
        Create memories and auto-prune old ones.

        Keeps only the 10 most recent memories per agent+user pair.
        Deletes oldest when new one added beyond limit.

        Args:
            vals_list (list): List of memory value dicts

        Returns:
            RecordSet: Created memory records
        """
        result = super().create(vals_list)

        # Prune old memories for each agent+user pair
        for memory in result:
            old_memories = self.search([
                ('agent_id', '=', memory.agent_id.id),
                ('user_id', '=', memory.user_id.id),
            ], order='create_date DESC', limit=10, offset=10)

            if old_memories:
                _logger.info(
                    'Pruning %d old memories for agent %s, user %s',
                    len(old_memories),
                    memory.agent_id.name,
                    memory.user_id.name,
                )
                old_memories.unlink()

        return result
